disabled_rules:
  - trailing_whitespace
  - line_length
  - type_body_length
  - file_length
  - function_body_length
  - identifier_name
  - large_tuple
  - multiple_closures_with_trailing_closure

opt_in_rules:
  - empty_count
  - empty_string
  - first_where
  - sorted_first_last
  - sorted_imports

excluded:
  - Pods
  - .build
  - DerivedData

line_length:
  warning: 150
  error: 200

type_body_length:
  warning: 400
  error: 500

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 80
  error: 100

