name: WLLT
options:
  bundleIdPrefix: com.wllt
  deploymentTarget:
    iOS: "15.0"
  developmentLanguage: en
  xcodeVersion: "15.0"
  usesTabs: false
  indentWidth: 2
  tabWidth: 2

packages:
  web3swift:
    url: https://github.com/skywinder/web3swift
    from: 3.0.0
  KeychainAccess:
    url: https://github.com/kishikawakatsumi/KeychainAccess
    from: 4.2.2

targets:
  WLLT:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: WLLT
        excludes:
          - "**/*.md"
          - "**/WalletConnectManager.swift"
          - "**/WalletConnectView.swift"
          - "**/SessionsView.swift"
          - "**/RequestView.swift"
    resources:
      - path: WLLT/Resources
        type: folder
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.wllt.app
      INFOPLIST_FILE: WLLT/Info.plist
      SWIFT_VERSION: "5.9"
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: ""
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ENABLE_PREVIEWS: YES
    dependencies:
      - package: web3swift
      - package: KeychainAccess
    frameworks:
      - LocalAuthentication
      - AVFoundation
    info:
      path: WLLT/Info.plist
      properties:
        UILaunchScreen: {}
        UIRequiredDeviceCapabilities: [armv7]
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSFaceIDUsageDescription: "Use Face ID to secure your wallet"
        NSLocalNetworkUsageDescription: "Connect to blockchain networks"

